#!/bin/bash

# Week 5 Agent 功能测试脚本
# 直接在命令行输出测试结果

echo "=========================================="
echo "Week 5 Agent 功能测试"
echo "=========================================="
echo ""

# 测试 1: Test Architect Agent
echo "【测试 1】Test Architect Agent"
echo "----------------------------------------"
echo "Prompt: 分析 test/src/auth.c 的测试策略"
echo ""
echo "预期成果："
echo "  1. 列出 auth.c 中的所有函数"
echo "  2. 分析每个函数的复杂度"
echo "  3. 识别关键路径（如 authenticate_user）"
echo "  4. 输出优先级排序的测试计划"
echo "  5. 建议单元测试和集成测试的比例"
echo ""
echo "验证点："
echo "  ✓ Agent 能使用 TestGraphTool 查询函数"
echo "  ✓ Agent 能使用 LSPTool 分析复杂度"
echo "  ✓ 输出包含具体的文件路径和行号"
echo "  ✓ 测试策略合理且可执行"
echo ""
read -p "按回车继续下一个测试..."
echo ""

# 测试 2: Unit Test Engineer Agent
echo "【测试 2】Unit Test Engineer Agent"
echo "----------------------------------------"
echo "Prompt: 为 test/src/auth.c 中的 authenticate_user 函数生成单元测试"
echo ""
echo "预期成果："
echo "  1. 生成完整的 C 测试代码（使用 Unity 框架）"
echo "  2. 包含 happy path 测试"
echo "  3. 包含边界条件测试（NULL 指针、空字符串）"
echo "  4. 包含错误处理测试"
echo "  5. 每个测试用例有清晰的命名"
echo ""
echo "示例输出："
echo "  void test_authenticate_user_valid_credentials(void) {"
echo "      // Arrange"
echo "      const char* username = \"admin\";"
echo "      const char* password = \"password123\";"
echo "      "
echo "      // Act"
echo "      int result = authenticate_user(username, password);"
echo "      "
echo "      // Assert"
echo "      TEST_ASSERT_EQUAL(0, result);"
echo "  }"
echo ""
echo "验证点："
echo "  ✓ 代码语法正确，可编译"
echo "  ✓ 覆盖所有代码分支"
echo "  ✓ 使用正确的测试框架（Unity）"
echo "  ✓ 遵循 AAA 模式（Arrange-Act-Assert）"
echo ""
read -p "按回车继续下一个测试..."
echo ""

# 测试 3: Integration Test Engineer Agent
echo "【测试 3】Integration Test Engineer Agent"
echo "----------------------------------------"
echo "Prompt: 为 test/src/auth.c 和 test/src/session.c 的交互生成集成测试"
echo ""
echo "预期成果："
echo "  1. 识别 auth 和 session 模块的集成点"
echo "  2. 生成测试登录后创建 session 的流程"
echo "  3. 测试 session 验证依赖 auth 状态"
echo "  4. 测试错误传播（auth 失败 → session 不创建）"
echo "  5. 包含 setup/teardown 清理资源"
echo ""
echo "示例输出："
echo "  void test_login_creates_valid_session(void) {"
echo "      // Arrange"
echo "      setup_test_database();"
echo "      "
echo "      // Act"
echo "      int auth_result = authenticate_user(\"user\", \"pass\");"
echo "      session_t* session = create_session(auth_result);"
echo "      "
echo "      // Assert"
echo "      TEST_ASSERT_NOT_NULL(session);"
echo "      TEST_ASSERT_TRUE(is_session_valid(session));"
echo "      "
echo "      // Cleanup"
echo "      destroy_session(session);"
echo "      teardown_test_database();"
echo "  }"
echo ""
echo "验证点："
echo "  ✓ 测试覆盖模块间交互"
echo "  ✓ 包含数据流验证"
echo "  ✓ 包含错误传播测试"
echo "  ✓ 资源清理完整"
echo ""
read -p "按回车继续下一个测试..."
echo ""

# 测试 4: Test Reviewer Agent
echo "【测试 4】Test Reviewer Agent"
echo "----------------------------------------"
echo "Prompt: 审查 test/tests/test_auth.c 的测试质量"
echo ""
echo "预期成果："
echo "  1. 识别测试代码中的问题"
echo "  2. 按严重程度分类（Critical/High/Medium/Low）"
echo "  3. 提供具体的行号和代码示例"
echo "  4. 给出改进建议"
echo "  5. 最终给出审查结论（Approve/Request Changes/Reject）"
echo ""
echo "示例输出："
echo "  ## Test Review for test/tests/test_auth.c"
echo "  "
echo "  ### Summary"
echo "  - Total tests: 5"
echo "  - Overall quality: Good"
echo "  - Critical issues: 1"
echo "  "
echo "  ### Critical Issues"
echo "  1. **Missing NULL check** (Line 23)"
echo "     - Problem: authenticate_user called without NULL check"
echo "     - Impact: Potential segfault"
echo "     - Fix: Add TEST_ASSERT_NOT_NULL before calling"
echo "  "
echo "  ### Overall Recommendation: Request Changes"
echo ""
echo "验证点："
echo "  ✓ 能识别常见测试坏味道"
echo "  ✓ 问题分类合理"
echo "  ✓ 建议具体可操作"
echo "  ✓ 包含代码示例"
echo ""
read -p "按回车继续下一个测试..."
echo ""

# 测试 5: Test Diagnostician Agent
echo "【测试 5】Test Diagnostician Agent"
echo "----------------------------------------"
echo "Prompt: 诊断测试失败"
echo "  错误信息: Segmentation fault (core dumped)"
echo "  堆栈: test_auth.c:45 in authenticate_user()"
echo "  上下文: 测试 test_authenticate_user_null_password 失败"
echo ""
echo "预期成果："
echo "  1. 分析失败类型（ENVIRONMENT/TEST_CODE/SOURCE_CODE/FLAKY）"
echo "  2. 识别根本原因（NULL 指针未检查）"
echo "  3. 提供修复建议"
echo "  4. 查询历史是否有类似失败"
echo "  5. 给出置信度评分"
echo ""
echo "示例输出："
echo "  ## Test Failure Diagnosis"
echo "  "
echo "  ### Failure Classification"
echo "  Type: SOURCE_CODE"
echo "  Confidence: 95%"
echo "  "
echo "  ### Root Cause Analysis"
echo "  The function authenticate_user() does not check for NULL"
echo "  password before calling strlen(), causing segfault."
echo "  "
echo "  ### Fix Recommendation"
echo "  Add NULL check at the beginning of authenticate_user():"
echo "  "
echo "  if (password == NULL) {"
echo "      return -1; // Invalid input"
echo "  }"
echo "  "
echo "  ### Historical Pattern"
echo "  Similar NULL pointer failures found 3 times in auth module"
echo "  (查询自 TestMemoryTool)"
echo ""
echo "验证点："
echo "  ✓ 失败分类准确"
echo "  ✓ 根因分析合理"
echo "  ✓ 修复建议可行"
echo "  ✓ 能查询历史数据"
echo ""

echo ""
echo "=========================================="
echo "测试完成"
echo "=========================================="
echo ""
echo "如何运行这些测试："
echo ""
echo "方式 1: 在 Claude Code 中直接输入 prompt"
echo "  例如: 使用 test-architect Agent 分析 test/src/auth.c"
echo ""
echo "方式 2: 使用 Agent 工具（如果支持）"
echo "  例如: @test-architect 分析 test/src/auth.c"
echo ""
echo "方式 3: 通过 AgentTool 调用"
echo "  需要在 Week 6 实现 TestOrchestrator 后才能使用"
echo ""
echo "注意事项："
echo "  1. Agent 文件必须在 .claude/agents/ 目录下"
echo "  2. 确保 frontmatter 格式正确（name, description, model）"
echo "  3. Agent 需要能访问相应的 Tool（TestGraphTool 等）"
echo "  4. 某些功能需要先有测试数据（如 TestMemoryTool 的历史记录）"
echo ""
