/**
 * Fix Executor - Execute actual fixes for test failures
 *
 * Provides functions to execute the fix strategies generated by the ReAct engine.
 * This module handles the actual execution of fixes including running shell commands,
 * modifying files, and managing the execution environment.
 */

import { FailureType, Language, TestFailureInfo, HealingResult } from './reactEngine.js'
import { executeFix, FixActionResult } from './fixStrategies.js'
import { generateReport, generateTextReport } from './fixReport.js'

// Execution result
export interface FixExecutionResult {
  success: boolean
  action: string
  output: string
  error?: string
  filesModified?: string[]
  commandsRun?: string[]
}

// Executor configuration
export interface ExecutorConfig {
  dryRun: boolean
  maxCommands: number
  timeout: number
  workingDir?: string
}

// Default configuration
const DEFAULT_CONFIG: ExecutorConfig = {
  dryRun: true,  // Default to dry run for safety
  maxCommands: 10,
  timeout: 30000
}

/**
 * Execute fix strategies based on classification
 */
export async function executeHealingFix(
  result: HealingResult,
  testInfo: TestFailureInfo,
  config: Partial<ExecutorConfig> = {}
): Promise<FixExecutionResult> {
  const cfg = { ...DEFAULT_CONFIG, ...config }

  // Try to execute fix based on failure type
  const fixResult = await executeFix(result.language, result.failureType, testInfo)

  if (!fixResult.success) {
    return {
      success: false,
      action: fixResult.action,
      output: '',
      error: fixResult.details || 'No fix available'
    }
  }

  // In dry run mode, just return what would be done
  if (cfg.dryRun) {
    return {
      success: true,
      action: fixResult.action,
      output: `Would execute: ${fixResult.fix}`,
      commandsRun: [fixResult.fix || ''].filter(Boolean)
    }
  }

  // Execute the actual fix
  return executeCommand(fixResult.fix || '', cfg)
}

/**
 * Execute a shell command
 */
async function executeCommand(
  command: string,
  config: ExecutorConfig
): Promise<FixExecutionResult> {
  if (!command) {
    return {
      success: false,
      action: 'execute',
      output: '',
      error: 'Empty command'
    }
  }

  try {
    // Use Bun for command execution
    const process = Bun.spawn(command.split(' '), {
      cwd: config.workingDir || process.cwd(),
      timeout: config.timeout
    })

    const output = await new Response(process.stdout).text()
    const error = await new Response(process.stderr).text()

    if (process.exitCode !== 0) {
      return {
        success: false,
        action: 'execute',
        output,
        error: error || `Exit code: ${process.exitCode}`,
        commandsRun: [command]
      }
    }

    return {
      success: true,
      action: 'execute',
      output,
      commandsRun: [command]
    }
  } catch (err: any) {
    return {
      success: false,
      action: 'execute',
      output: '',
      error: err.message,
      commandsRun: [command]
    }
  }
}

/**
 * Run multiple commands in sequence
 */
async function executeCommands(
  commands: string[],
  config: ExecutorConfig
): Promise<FixExecutionResult> {
  const results: FixExecutionResult[] = []
  let allSuccess = true

  for (const cmd of commands.slice(0, config.maxCommands)) {
    const result = await executeCommand(cmd, config)
    results.push(result)
    if (!result.success) {
      allSuccess = false
      break
    }
  }

  return {
    success: allSuccess,
    action: 'execute-commands',
    output: results.map(r => r.output).join('\n'),
    error: results.find(r => !r.success)?.error,
    commandsRun: results.map(r => r.action)
  }
}

/**
 * Apply fixes to test file
 */
export async function applyTestFix(
  testFile: string,
  fixType: string,
  content: string
): Promise<{ success: boolean; error?: string }> {
  // Read the file
  const fileContent = await Bun.file(testFile).text()

  // Apply the fix based on type
  let newContent: string

  switch (fixType) {
    case 'fix-mock':
      // Fix mock configuration
      newContent = content
      break
    case 'fix-assertion':
      // Fix assertion
      newContent = content
      break
    default:
      return { success: false, error: `Unknown fix type: ${fixType}` }
  }

  // Write the file
  await Bun.write(testFile, newContent)

  return { success: true }
}

/**
 * Quick execute fix - convenience wrapper
 */
export async function quickFix(
  testName: string,
  testFile: string,
  error: string,
  stackTrace?: string,
  dryRun: boolean = true
): Promise<{
  healingResult: HealingResult
  executionResult: FixExecutionResult
  report: string
}> {
  // Import ReActEngine dynamically to avoid circular imports
  const { quickHeal } = await import('./reactEngine.js')

  // Run healing
  const healingResult = await quickHeal(testName, testFile, error, stackTrace)

  // Execute fix
  const testInfo: TestFailureInfo = { testName, testFile, error, stackTrace }
  const executionResult = await executeHealingFix(healingResult, testInfo, { dryRun })

  // Generate report
  const report = generateTextReport(healingResult, testName)

  return { healingResult, executionResult, report }
}

export {
  DEFAULT_CONFIG,
  type ExecutorConfig,
  type FixExecutionResult
}
